============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/bridge/code/incubyte
plugins: Faker-24.4.0, anyio-4.4.0
collected 4 items

test.py ...F                                                             [100%]

=================================== FAILURES ===================================
______________ TestAddFunction.test_add_with_different_delimiters ______________

self = <test.TestAddFunction object at 0x73db14d036d0>

    def test_add_with_different_delimiters(self):
        response = add('1\n2,3')
>       assert response == 6
E       assert 3 == 6

test.py:22: AssertionError
=========================== short test summary info ============================
FAILED test.py::TestAddFunction::test_add_with_different_delimiters - assert ...
========================= 1 failed, 3 passed in 0.04s ==========================
