============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/bridge/code/incubyte
plugins: Faker-24.4.0, anyio-4.4.0
collected 5 items

test.py ....F                                                            [100%]

=================================== FAILURES ===================================
______________ TestAddFunction.test_support_multiple_delimieters _______________

self = <test.TestAddFunction object at 0x7542b0d77bb0>

    def test_support_multiple_delimieters(self):
        response = add('//;\n1;2;3')
>       assert response == 6
E       assert 0 == 6

test.py:26: AssertionError
=========================== short test summary info ============================
FAILED test.py::TestAddFunction::test_support_multiple_delimieters - assert 0...
========================= 1 failed, 4 passed in 0.04s ==========================
